import type { Category } from '@/types/category';
import type { ExpenseComment } from '@/types/comment';
import type { Expense, ExpenseFilters, ExpenseId, ExpenseInput } from '@/types/expense';
import type { GroupInput, GroupWithMembers } from '@/types/group';
import type { Participant, ParticipantId, ParticipantInput } from '@/types/participant';
import type { RecurringExpense, RecurringExpenseInput } from '@/types/recurring';
import type { Settlement, SettlementInput } from '@/types/settlement';
import type { LoginInput, RegisterInput, User } from '@/types/user';

/**
 * The persistence contracts.
 *
 * Everything above this line — services, hooks, screens — depends only on these
 * interfaces. Today they are backed by SQLite; swapping in an HTTP-backed
 * implementation later is a change of infrastructure, not of the application.
 *
 * Two rules keep that promise honest:
 * - ids are generated by the application, so they survive a move to a backend
 *   that assigns its own;
 * - nothing here exposes SQL, rows, or a transaction handle.
 */

export interface AuthRepository {
  register(input: RegisterInput): Promise<User>;
  login(input: LoginInput): Promise<User>;
  logout(): Promise<void>;
  /** The signed-in user restored from the persisted session, if any. */
  getCurrentUser(): Promise<User | null>;
  updateProfile(userId: string, changes: { name?: string; email?: string }): Promise<User>;
}

export interface ParticipantRepository {
  /** Everyone the user has saved, excluding themselves, newest name order. */
  listFriends(ownerUserId: string): Promise<Participant[]>;
  /** Friends plus the user's own row. */
  listAll(ownerUserId: string): Promise<Participant[]>;
  getById(id: ParticipantId): Promise<Participant | null>;
  getSelf(ownerUserId: string): Promise<Participant | null>;
  /** Creates the participant row that represents the user. Idempotent. */
  ensureSelf(ownerUserId: string, name: string, email?: string): Promise<Participant>;
  create(ownerUserId: string, input: ParticipantInput): Promise<Participant>;
  update(id: ParticipantId, input: ParticipantInput): Promise<Participant>;
  /** Soft delete: past expenses keep referring to the person. */
  remove(id: ParticipantId): Promise<void>;
  /** Names of people who appear in expenses, for the quick-add row. */
  search(ownerUserId: string, term: string): Promise<Participant[]>;
}

export interface GroupRepository {
  list(ownerUserId: string): Promise<GroupWithMembers[]>;
  getById(id: string): Promise<GroupWithMembers | null>;
  create(ownerUserId: string, input: GroupInput): Promise<GroupWithMembers>;
  update(id: string, input: GroupInput): Promise<GroupWithMembers>;
  remove(id: string): Promise<void>;
  addMember(groupId: string, participantId: ParticipantId): Promise<void>;
  removeMember(groupId: string, participantId: ParticipantId): Promise<void>;
}

export interface ExpenseRepository {
  list(ownerUserId: string, filters?: ExpenseFilters): Promise<Expense[]>;
  getById(id: ExpenseId): Promise<Expense | null>;
  /** Writes the expense, its payers, splits and items atomically. */
  create(ownerUserId: string, input: ExpenseInput): Promise<Expense>;
  /** Replaces the expense and all of its child rows atomically. */
  update(id: ExpenseId, input: ExpenseInput): Promise<Expense>;
  /** Soft delete, so the financial record survives. */
  remove(id: ExpenseId): Promise<void>;
  restore(id: ExpenseId): Promise<void>;
  setReceipt(id: ExpenseId, receiptUri: string | null): Promise<void>;
}

export interface SettlementRepository {
  list(ownerUserId: string, options?: { groupId?: string; limit?: number }): Promise<Settlement[]>;
  /** Settlements recorded against one expense, i.e. per-share "mark paid". */
  listForExpense(expenseId: ExpenseId): Promise<Settlement[]>;
  getById(id: string): Promise<Settlement | null>;
  create(ownerUserId: string, input: SettlementInput): Promise<Settlement>;
  remove(id: string): Promise<void>;
  /** Removes the settlement recorded for one participant on one expense. */
  removeForExpenseParticipant(expenseId: ExpenseId, participantId: ParticipantId): Promise<void>;
}

export interface CommentRepository {
  list(expenseId: ExpenseId): Promise<ExpenseComment[]>;
  create(
    expenseId: ExpenseId,
    authorParticipantId: ParticipantId,
    comment: string
  ): Promise<ExpenseComment>;
  remove(id: string): Promise<void>;
}

export interface CategoryRepository {
  list(): Promise<Category[]>;
  getById(id: string): Promise<Category | null>;
}

export interface RecurringExpenseRepository {
  list(ownerUserId: string): Promise<RecurringExpense[]>;
  getById(id: string): Promise<RecurringExpense | null>;
  create(ownerUserId: string, input: RecurringExpenseInput): Promise<RecurringExpense>;
  update(id: string, input: RecurringExpenseInput): Promise<RecurringExpense>;
  setActive(id: string, isActive: boolean): Promise<void>;
  remove(id: string): Promise<void>;
  /** Templates whose next run is at or before `asOf`. */
  listDue(ownerUserId: string, asOf: string): Promise<RecurringExpense[]>;
  markRun(id: string, ranAt: string, nextDueAt: string): Promise<void>;
}
